# Makefile fuer das pes_thigh-Plugin
# Entspricht dem Aufbau der Beispiel-Plugins im GoldHEN_Plugins_Repository.
# Wird von der GitHub-Actions-CI des Repos automatisch mitgebaut.

TARGET  = pes_thigh
CFLAGS  = -Wall -O2
OUTDIR  = ../../bin/plugins

include $(GOLDHEN_SDK)/make/plugin.mk
